### ISSUE TITLE
com.sun.jna.platform.win32.Win32Exception: The logon attempt failed causes a 500 status error

### ISSUE THREAD

**Issue by dblock** [dblock/waffle#203]
Tomcat valve isn't catching a Win32 auth error, should be turning it into a 401.

```
com.sun.jna.platform.win32.Win32Exception: The logon attempt failed
	waffle.windows.auth.impl.WindowsAuthProviderImpl.acceptSecurityToken(WindowsAuthProviderImpl.java:134)
	waffle.apache.NegotiateAuthenticator.authenticate(NegotiateAuthenticator.java:97)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1008)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:744)
```

Probably [here](https://github.com/dblock/waffle/blob/master/Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/NegotiateAuthenticator.java#L107).

![screen shot 2015-03-10 at 8 31 03 am](https://cloud.githubusercontent.com/assets/542335/6574900/d3c24bbc-c6ff-11e4-86b0-f9b203f50ec8.png)

**Comment by hazendaz** [comment]
This is exactly where a stack trace has blown for some time.  I wrote into the unit tests to prevent it as I didn't understand why.  Fixing this breaks the unit tests in the original areas so uncertain what that would happen then if this was in fact restoring original logic.  However, some minor rewriting of tests to not look at as much under this condition gets those working again.  I'm going to do a pull request but it needs good review before pulling it in for this.  I also want to look at the other issue on this I think is still outstanding to see the dates around this.

**Comment by hazendaz** [comment]
This appears to be issue  #107

**Comment by hazendaz** [comment]
Resolved in PR #206

**Comment by michaelkong** [comment]
I am using Waffle 1.8, since it was built on Sep 2015,  the bug fix should be in 1.8 already.  How come I am still seeing the same error?

**Comment by hazendaz** [comment]
Can you try version 1.8.1 and let me know if its a problem there?

**Comment by gargomanjr** [comment]
I have the same error with the 1.8.1 waffle version...Someone could help me¿?

**Comment by hazendaz** [comment]
Can you try 1.8.3 and let us know if the issue is present?

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gargomanjr** [comment]
Thanks hazendaz, but I couldn't download the 1.8.3 version, ¿Which repository should I use?

I fixed this error in my code extending WindowsAuthProviderImpl and throwing a AuthenticationServiceException instead of Win32Exception.

Then, I used the failureHandler to handle this issue and redirect to login page.

**Comment by gargomanjr** [comment]
version 1.8.3 fix the problem!thank you!!!!!!!!!

**Comment by hazendaz** [comment]
@gargomanjr Your welcome!
